### ISSUE TITLE
Allow extra RPC calls

### ISSUE THREAD

**Issue by ChaoticTempest** [near/near-api-providers-rs#3]
So for the sandbox, we need some extra ways to call into methods like `sandbox_patch_state`, but this is very local-node/sandbox specific, so no need to hardcode this. Instead, a general way of providing these extra methods/params would be very useful.

From my brief view of the code, we can potentially change up things like `ExperimentalRpcMethod` to be a trait like so:
```Rust
trait ExperimentalRpcMethod {
  fn method_and_params(&self) -> (&str, serde_json::Value);
}
```
which provides a generic way to input custom JSON RPC requests.

Or add in some other enum variant that would allow this generic behavior if `Experimental` needs to be reserved.

@frol @miraclx thoughts?

**Comment by miraclx** [comment]
Well, this crate was intended as a sort-of low-level interface that `near-api-rs` or any other generic client can base off of. It would generally be discouraged to use this crate directly and most downstream libraries would use one of those higher-level crates. So, it makes sense to host the intricacies here.
